### ISSUE TITLE
[Android][Bug][Teams]We are using our own custom element action set to render actions inside a container. We sometimes see that the app crashes when we make a call to ActionElementRenderer to render the buttons .

### ISSUE THREAD

**Issue by rednivrug15** [Microsoft/AdaptiveCards#1425]
Json payload 
```json
{
	"type": "AdaptiveCard",
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"version": "1.0.0",
	"body": [{
		"type": "TextBlock",
		"text": "here is card title",
		"size": "large",
		"weight": "bolder",
		"wrap": true
	}, {
		"type": "TextBlock",
		"text": "<p>here is card text</p>",
		"size": "medium",
		"weight": "default",
		"wrap": true
	}, {
		"type": "Container",
		"items": [{
			"type": "TextBlock",
			"text": "<p><strong>here is the section title</strong></p>",
			"size": "large",
			"weight": "bold",
			"wrap": true
		}, {
			"type": "ColumnSet",
			"columns": [{
				"type": "Column",
				"items": [{
					"type": "Image",
					"url": "https://urlp.asm.skype.com/v1/url/content?url=http%3a%2f%2fconnectorsdemo.azurewebsites.net%2fimages%2fMSC12_Oscar_002.jpg",
					"size": "medium",
					"style": "person"
				}],
				"width": "auto"
			}, {
				"type": "Column",
				"width": "stretch",
				"items": [{
					"type": "TextBlock",
					"text": "<p><a href=\"http://google.com\">here is activity title</a></p>",
					"size": "medium",
					"weight": "bold",
					"wrap": true
				}, {
					"type": "TextBlock",
					"text": "<p>here is activity sbtitle</p>",
					"size": "medium",
					"weight": "default",
					"wrap": true
				}, {
					"type": "TextBlock",
					"text": "<p>here is activity text</p>",
					"size": "medium",
					"weight": "default",
					"wrap": true
				}]
			}]
		}, {
			"type": "TextBlock",
			"text": "<p>here is the section text</p>",
			"size": "medium",
			"weight": "default",
			"wrap": true
		}, {
			"type": "FactSet",
			"facts": [{
				"title": "Item 1 - name",
				"value": "<p>Item 1 - here is item value</p>"
			}, {
				"title": "Item 2 - name",
				"value": "<p>Item 2 - here is item value</p>"
			}]
		}, {
			"type": "ImageSet",
			"imageSize": "medium",
			"images": [{
				"type": "Image",
				"url": "https://urlp.asm.skype.com/v1/url/content?url=https%3a%2f%2fscontent-sea1-1.xx.fbcdn.net%2fv%2ft1.0-9%2f12187712_10206983501483403_4173446256495178673_n.jpg%3foh%3d923ebeb3e305af9245734612c771f9b7%26oe%3d5A26B5AE",
				"size": "medium",
				"style": "default"
			}, {
				"type": "Image",
				"url": "https://urlp.asm.skype.com/v1/url/content?url=http%3a%2f%2fconnectorsdemo.azurewebsites.net%2fimages%2fWIN12_Scene_01.jpg",
				"size": "medium",
				"style": "default"
			}, {
				"type": "Image",
				"url": "https://urlp.asm.skype.com/v1/url/content?url=http%3a%2f%2fconnectorsdemo.azurewebsites.net%2fimages%2fWIN12_Anthony_02.jpg",
				"size": "medium",
				"style": "default"
			}, {
				"type": "Image",
				"url": "https://urlp.asm.skype.com/v1/url/content?url=https%3a%2f%2fscontent-sea1-1.xx.fbcdn.net%2fv%2ft1.0-9%2f12187712_10206983501483403_4173446256495178673_n.jpg%3foh%3d923ebeb3e305af9245734612c771f9b7%26oe%3d5A26B5AE",
				"size": "medium",
				"style": "default"
			}, {
				"type": "Image",
				"url": "https://urlp.asm.skype.com/v1/url/content?url=http%3a%2f%2fconnectorsdemo.azurewebsites.net%2fimages%2fWIN12_Scene_01.jpg",
				"size": "medium",
				"style": "default"
			}, {
				"type": "Image",
				"url": "https://urlp.asm.skype.com/v1/url/content?url=http%3a%2f%2fconnectorsdemo.azurewebsites.net%2fimages%2fWIN12_Anthony_02.jpg",
				"size": "medium",
				"style": "default"
			}]
		}]
	}, {
		"type": "ActionSet",
		"actions": [{
			"type": "Action.ShowCard",
			"title": "Multiple Choice",
			"card": {
				"type": "AdaptiveCard",
				"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
				"version": "1.0.0",
				"body": [{
					"type": "TextBlock",
					"text": "Pick multiple options",
					"size": "medium",
					"weight": "default",
					"wrap": true
				}, {
					"type": "Input.ChoiceSet",
					"id": "isRequiredlist-1isMultichoice",
					"value": "1,3",
					"choices": [{
						"title": "Choice 1",
						"value": "1"
					}, {
						"title": "Choice 2",
						"value": "2"
					}, {
						"title": "Choice 3",
						"value": "3"
					}],
					"isMultiSelect": true,
					"style": "compact"
				}, {
					"type": "TextBlock",
					"text": "Pick multiple options",
					"size": "medium",
					"weight": "default",
					"wrap": true
				}, {
					"type": "Input.ChoiceSet",
					"id": "isRequiredlist-2isMultichoice",
					"value": "4,5",
					"choices": [{
						"title": "Choice 4",
						"value": "4"
					}, {
						"title": "Choice 5",
						"value": "5"
					}, {
						"title": "Choice 6",
						"value": "6"
					}],
					"isMultiSelect": true,
					"style": "compact"
				}, {
					"type": "TextBlock",
					"text": "Pick an options",
					"size": "medium",
					"weight": "default",
					"wrap": true
				}, {
					"type": "Input.ChoiceSet",
					"id": "list-3isMultichoice",
					"value": "b",
					"choices": [{
						"title": "Choice a",
						"value": "a"
					}, {
						"title": "Choice b",
						"value": "b"
					}, {
						"title": "Choice c",
						"value": "c"
					}],
					"isMultiSelect": false,
					"style": "expanded"
				}, {
					"type": "TextBlock",
					"text": "Pick an options",
					"size": "medium",
					"weight": "default",
					"wrap": true
				}, {
					"type": "Input.ChoiceSet",
					"id": "list-4isMultichoice",
					"value": "z",
					"choices": [{
						"title": "Choice x",
						"value": "x"
					}, {
						"title": "Choice y  super long super long super long super long super long super long super long super long super long super long",
						"value": "y"
					}, {
						"title": "Choice z",
						"value": "z"
					}],
					"isMultiSelect": false,
					"style": "compact"
				}],
				"actions": [{
					"type": "Action.Submit",
					"title": "Send",
					"data": {
						"target": "",
						"body": "{\"list1\":\"{{list-1.value}}\",\"list2\":\"{{list-2.value}}\",\"list3\":\"{{list-3.value}}\",\"list4\":\"{{list-4.value}}\"}",
						"bodyContentType": "",
						"id": "card-1-btn-1"
					}
				}]
			}
		}, {
			"type": "Action.ShowCard",
			"title": "Text Input",
			"card": {
				"type": "AdaptiveCard",
				"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
				"version": "1.0.0",
				"body": [{
					"type": "TextBlock",
					"text": "multiline, no maxLength",
					"size": "medium",
					"weight": "default",
					"wrap": true
				}, {
					"type": "Input.Text",
					"placeholder": "multiline, no maxLength",
					"id": "text-1isTextinput",
					"value": "Some text...",
					"isMultiline": true
				}, {
					"type": "TextBlock",
					"text": "single line, no maxLength",
					"size": "medium",
					"weight": "default",
					"wrap": true
				}, {
					"type": "Input.Text",
					"placeholder": "single line, no maxLength",
					"id": "text-2isTextinput",
					"value": "",
					"isMultiline": false
				}, {
					"type": "TextBlock",
					"text": "multiline, max len = 10, isRequired",
					"size": "medium",
					"weight": "default",
					"wrap": true
				}, {
					"type": "Input.Text",
					"placeholder": "multiline, max len = 10, isRequired",
					"id": "isRequiredtext-3isTextinput",
					"value": "",
					"isMultiline": true
				}, {
					"type": "TextBlock",
					"text": "single line, max len = 10, isRequired",
					"size": "medium",
					"weight": "default",
					"wrap": true
				}, {
					"type": "Input.Text",
					"placeholder": "single line, max len = 10, isRequired",
					"id": "isRequiredtext-4isTextinput",
					"value": "",
					"isMultiline": false
				}],
				"actions": [{
					"type": "Action.Submit",
					"title": "Send",
					"data": {
						"target": "",
						"body": "{\"text1\":\"{{text-1.value}}\",\"text2\":\"{{text-2.value}}\",\"text3\":\"{{text-3.value}}\",\"text4\":\"{{text-4.value}}\"}",
						"bodyContentType": "",
						"id": "card-2-btn-1"
					}
				}]
			}
		}, {
			"type": "Action.ShowCard",
			"title": "Date Input",
			"card": {
				"type": "AdaptiveCard",
				"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
				"version": "1.0.0",
				"body": [{
					"type": "TextBlock",
					"text": "date with time",
					"size": "medium",
					"weight": "default",
					"wrap": true
				}, {
					"type": "Input.Date",
					"placeholder": "date with time",
					"id": "isRequireddate-1isDate",
					"value": "2018-01-01"
				}, {
					"type": "Input.Time",
					"placeholder": "date with time",
					"id": "isRequireddate-1isTime",
					"value": "14:53:0"
				}, {
					"type": "TextBlock",
					"text": "date only",
					"size": "medium",
					"weight": "default",
					"wrap": true
				}, {
					"type": "Input.Date",
					"placeholder": "date only",
					"id": "date-2isDate",
					"value": ""
				}],
				"actions": [{
					"type": "Action.Submit",
					"title": "Send",
					"data": {
						"target": "",
						"body": "{\"date1\":\"{{date-1.value}}\",\"date2\":\"{{date-2.value}}\"}",
						"bodyContentType": "",
						"id": "card-3-btn-1"
					}
				}]
			}
		}, {
			"type": "Action.OpenUrl",
			"title": "View Action",
			"url": "http://microsoft.com"
		}, {
			"type": "Action.OpenUrl",
			"title": "Open Uri",
			"url": "http://microsoft.com"
		}]
	}]
}
```

ActionSetRenderer Code :
```java
       public class ActionSetRenderer extends BaseCardElementRenderer {
    private static final String TAG = "ActionSetRenderer";
    @Override
    public View render(RenderedAdaptiveCard renderedAdaptiveCard,
                       Context context,
                       FragmentManager fragmentManager,
                       ViewGroup viewGroup,
                       BaseCardElement baseCardElement,
                       ICardActionHandler iCardActionHandler,
                       HostConfig hostConfig,
                       ContainerStyle containerStyle) {
       /*The below line is line number 45 basCardElement.findImplObj()*/
        if (!(baseCardElement.findImplObj() instanceof ActionSet)) {
            ApplicationUtilities.getLoggerInstance().log(LogPriority.ERROR, TAG, "Unable to convert base card element to Action Set object");
            return null;
        }

        BaseCardElement actionSetElement = baseCardElement.findImplObj();

        ActionSet actionSet = (ActionSet) actionSetElement; //This is the way SDK suggests to cast
        int maxActions = (int) hostConfig.getActions().getMaxActions(); //Max number of actions allowed
        List<BaseActionElement> baseActionElements = actionSet.getActions();
        int numberOfActions = baseActionElements.size();

        LinearLayout rootLayout = new LinearLayout(context);
        rootLayout.setLayoutParams(new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT));
        rootLayout.setOrientation(LinearLayout.VERTICAL);

        //First element will contain the buttons , second to show inputs etc
        LinearLayout actionLayout = new LinearLayout(context);
        actionLayout.setLayoutParams(new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT));
        actionLayout.setPadding(0, 0, 0, 0);
        LinearLayout actionButtonsLayout = new LinearLayout(context);
        actionButtonsLayout.setLayoutParams(new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT)); //Allow full width
        actionButtonsLayout.setOrientation(LinearLayout.HORIZONTAL);
        actionLayout.addView(actionButtonsLayout);
        rootLayout.addView(actionLayout);

        //Second element is to show cards
        LinearLayout showCardLayout = new LinearLayout(context);
        showCardLayout.setLayoutParams(new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT));
        rootLayout.addView(showCardLayout);

        viewGroup.addView(rootLayout);

        for (int i = 0; i < numberOfActions && i < maxActions; i++) {
            BaseActionElement actionElement = baseActionElements.get(i);
           
            ActionElementRenderer.getInstance().render(renderedAdaptiveCard, context, fragmentManager, actionButtonsLayout, actionElement, iCardActionHandler, hostConfig);
        }

       
        HorizontalScrollView horizontalScrollView = new HorizontalScrollView(context);
        horizontalScrollView.setHorizontalScrollBarEnabled(false);
        actionLayout.removeAllViews();
        horizontalScrollView.addView(actionButtonsLayout);

        //Remove actionsButton layout from Linear layout

        actionLayout.addView(horizontalScrollView);

        return actionButtonsLayout;
    }
}
```
Stack trace of the exception : 

`05-03 22:24:33.512 25848-25910/com.microsoft.skype.teams.dev E/ApplicationNotResponding: ProcessId: 25848, Thread: |ANR-WatchDog|, Application is not responding
                                                                                         com.github.anrwatchdog.ANRError: Application Not Responding
                                                                                         Caused by: com.github.anrwatchdog.ANRError$$$_Thread: main (state = RUNNABLE)
                                                                                             at com.microsoft.skype.teams.views.widgets.adaptivecard.ActionSetRenderer.render(ActionSetRenderer.java:45)
                                                                                             at io.adaptivecards.renderer.registration.CardRendererRegistration.render(CardRendererRegistration.java:125)
                                                                                             at io.adaptivecards.renderer.AdaptiveCardRenderer.internalRender(AdaptiveCardRenderer.java:186)
                                                                                             at io.adaptivecards.renderer.AdaptiveCardRenderer.render(AdaptiveCardRenderer.java:120)
                                                                                             at com.microsoft.skype.teams.views.widgets.AdaptiveCardView.setView(AdaptiveCardView.java:63)
                                                                                             at com.microsoft.skype.teams.views.widgets.AdaptiveCardView.setAdaptiveCard(AdaptiveCardView.java:45)
                                                                                             at com.microsoft.skype.teams.databinding.CardO365ConversationItemBinding.executeBindings(CardO365ConversationItemBinding.java:131)
                                                                                             at android.databinding.ViewDataBinding.executeBindingsInternal(ViewDataBinding.java:437)
                                                                                             at android.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:409)
                                                                                             at com.microsoft.skype.teams.views.widgets.richtext.CardItemBlock.getView(CardItemBlock.java:180)
                                                                                             at com.microsoft.skype.teams.views.widgets.richtext.RichTextView.setBlocks(RichTextView.java:219)
                                                                                             at com.microsoft.skype.teams.views.widgets.richtext.RichTextView.setBlocks(RichTextView.java:43)
                                                                                             at com.microsoft.skype.teams.databinding.ConversationItemBinding.executeBindings(ConversationItemBinding.java:664)
                                                                                             at android.databinding.ViewDataBinding.executeBindingsInternal(ViewDataBinding.java:437)
                                                                                             at android.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:409)
                                                                                             at me.tatarka.bindingcollectionadapter2.BindingRecyclerViewAdapter.onBindBinding(BindingRecyclerViewAdapter.java:78)
                                                                                             at me.tatarka.bindingcollectionadapter2.BindingRecyclerViewAdapter.onBindViewHolder(BindingRecyclerViewAdapter.java:147)
                                                                                             at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
                                                                                             at me.tatarka.bindingcollectionadapter2.BindingRecyclerViewAdapter.onBindViewHolder(BindingRecyclerViewAdapter.java:156)
                                                                                             at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
                                                                                             at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
                                                                                             at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
                                                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
                                                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
                                                                                             at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
                                                                                             at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
                                                                                             at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
                                                                                             at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
                                                                                             at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
                                                                                             at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
                                                                                             at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
                                                                                             at android.view.View.layout(View.java:18874)
                                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5954)
                                                                                             at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:606)
                                                                                             at android.view.View.layout(View.java:18874)
                                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5954)
                                                                                             at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                                             at android.view.View.layout(View.java:18874)
                                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5954)
                                                                                             at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                                             at android.view.View.layout(View.java:18874)
                                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5954)
                                                                                             at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                                         	at com.microsoft.teams.core.views.widgets.statelayout.St`

**Comment by msmoosa** [comment]
To clarify, it isnt really a crash but an ANR, the findImplObj() is probably taking too long to return

**Comment by khouzam** [comment]
This has been merged.

**Comment by shalinijoshi19** [comment]
@rednivrug15 are you still continuing to see this issue for the Android renderer with the version of AC you are on? Also what version of AC are you using again today? Thanks!

**Comment by shalinijoshi19** [comment]
@almedina-ms could you add a test case for this specific scenario please as follow up.. Meanwhile closing this as not-repro. 
@rednivrug15 please do get back if you are seeing this again
