### ISSUE TITLE
Input.ChoiceSet stay blank in Android

### ISSUE THREAD

**Issue by ThomasNeolink** [microsoft/AdaptiveCards#1912]
What platform is your issue or question related to? 
* Android
compileSdkVersion 26
buildToolsVersion '26.0.0'

I use the library 'io.adaptivecards:adaptivecards-android:1.0.4' and DirectLine with API REST 3.0 to exchange with the bot azure.
I receive a AdaptiveCard from the Bot on my tablet SQOOL (Android 5.0 API 21)
and my answers stay blank/ invisible.
I can select one and send the correct value of my choice.

![screenshot_2018-09-14-14-47-47](https://user-images.githubusercontent.com/25346010/45556185-f0a8ac00-b83a-11e8-88a8-da7547023aba.png)

I havn't this issue with a Samsung SM T580(Android 7.0 API 24).

```
{  
   "activities":[  
      {  
         "type":"message",
         "id":"5KvhcJEBvUaEVU5vW0tO13|0000003",
         "timestamp":"2018-09-14T14:40:52.6853575Z",
         "localTimestamp":"2018-09-14T14:40:52.628+00:00",
         "channelId":"directline",
         "from":{  
            "id":"Jda-Bot-Jeanette",
            "name":"Jda-Bot-Jeanette"
         },
         "conversation":{  
            "id":"5KvhcJEBvUaEVU5vW0tO13"
         },
         "inputHint":"acceptingInput",
         "attachments":[  
            {  
               "contentType":"application/vnd.microsoft.card.adaptive",
               "content":{  
                  "type":"AdaptiveCard",
                  "version":"1.0",
                  "body":[  
                     {  
                        "type":"TextBlock",
                        "size":"large",
                        "weight":"bolder",
                        "text":"Voici les résultats",
                        "wrap":true
                     },
                     {  
                        "type":"Input.ChoiceSet",
                        "id":"code**_1_10234",
                        "style":"expanded",
                        "isMultiSelect":false,
                        "choices":[  
                           {  
                              "title":"Intervention technique en contrôle essai qualité en électricité et électronique",
                              "value":"H04"
                           },
                           {  
                              "title":"Études et développement informatique",
                              "value":"M05"
                           },
                           {  
                              "title":"Installation et maintenance télécoms et courants faibles",
                              "value":"I17"
                           },
                           {  
                              "title":"Intervention technique en formulation et analyse sensorielle",
                              "value":"H05"
                           }
                        ]
                     }
                  ],
                  "actions":[  
                     {  
                        "type":"Action.Submit",
                        "data":{  
                           "id":"code**_1_10234",
                           "min":null,
                           "max":null
                        },
                        "title":"Valider"
                     },
                     {  
                        "type":"Action.Submit",
                        "data":"autre",
                        "title":"Faire une nouvelle recherche"
                     }
                  ]
               }
            }
         ],
         "replyToId":"5KvhcJEBvUaEVU5vW0tO13|0000002"
      }
   ],
   "watermark":"3"
}
```

**Comment by khouzam** [comment]
Hi @ThomasNeolink,

I've tried your card on our test app on 2 emulators with API 21 (5.0 Lollipop) and I can see the text without problem. This was both our `release/1.0` branch and the current `master` branch. Would you be able to try our test app with your SQOOL device?

**Comment by ThomasNeolink** [comment]
In order to be certain of being in a good environment, I have uninstalled and reinstalled android studio on its latest version 3.2.
My project runs with gradle update 3.2,   your _**master**_ dont work with it...
but with 3.0.1 (like your code) an error appears :

![erreurtoolchain](https://user-images.githubusercontent.com/25346010/46135572-d06aeb00-c245-11e8-872c-d44177878a0e.JPG)

The problem is caused by the upgrade of NDK in Android Studio to NDK v17. This version has a different structure of tools...
We have to use obsolete releases of the Android NDK to fix it...
I havnt seen any example of card with choice in "ACTION.OPENURL"

After that, a new error appears if i want show all card..
`E/HW-JPEG-DEC: [HME_JPEG_DEC_Delete](3298): HME_JPEG_DEC_Delete: decoder_ctx=null
    [HME_JPEG_DEC_Delete](3298): HME_JPEG_DEC_Delete: decoder_ctx=null
E/HW-JPEG-DEC: [HME_JPEG_DEC_Delete](3298): HME_JPEG_DEC_Delete: decoder_ctx=null
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.example.mobilechatapp, PID: 26922
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:330)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:255)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:776)
     Caused by: android.util.AndroidRuntimeException: Animators may only be run on Looper threads
        at android.animation.ValueAnimator.start(ValueAnimator.java:969)
        at android.animation.ValueAnimator.start(ValueAnimator.java:1010)
        at android.animation.ObjectAnimator.start(ObjectAnimator.java:852)
        at android.animation.AnimatorSet.start(AnimatorSet.java:678)
        at android.animation.AnimatorSet.onChildAnimatorEnded(AnimatorSet.java:807)
        at android.animation.AnimatorSet.start(AnimatorSet.java:640)
        at android.animation.AnimatorSet.start(AnimatorSet.java:678)
        at android.animation.AnimatorSet.onChildAnimatorEnded(AnimatorSet.java:807)
        at android.animation.AnimatorSet.start(AnimatorSet.java:640)
        at android.animation.AnimatorSet.start(AnimatorSet.java:678)
        at android.animation.AnimatorSet.onChildAnimatorEnded(AnimatorSet.java:807)
        at android.animation.AnimatorSet.start(AnimatorSet.java:640)
        at android.graphics.drawable.AnimatedVectorDrawable$VectorDrawableAnimatorUI.start(AnimatedVectorDrawable.java:900)
        at android.graphics.drawable.AnimatedVectorDrawable.start(AnimatedVectorDrawable.java:699)
        at android.graphics.drawable.AnimatedStateListDrawable$AnimatedVectorDrawableTransition.start(AnimatedStateListDrawable.java:339)
        at android.graphics.drawable.AnimatedStateListDrawable.selectTransition(AnimatedStateListDrawable.java:226)
        at android.graphics.drawable.AnimatedStateListDrawable.onStateChange(AnimatedStateListDrawable.java:146)
        at android.graphics.drawable.Drawable.setState(Drawable.java:732)
        at android.widget.CompoundButton.drawableStateChanged(CompoundButton.java:475)
        at android.view.View.refreshDrawableState(View.java:18091)
        at android.widget.CompoundButton.setChecked(CompoundButton.java:146)
        at io.adaptivecards.renderer.input.ChoiceSetInputRenderer.renderRadioGroup(ChoiceSetInputRenderer.java:119)
        at io.adaptivecards.renderer.input.ChoiceSetInputRenderer.render(ChoiceSetInputRenderer.java:223)
        at io.adaptivecards.renderer.registration.CardRendererRegistration.render(CardRendererRegistration.java:247)
        at io.adaptivecards.renderer.AdaptiveCardRenderer.internalRender(AdaptiveCardRenderer.java:182)
        at io.adaptivecards.renderer.AdaptiveCardRenderer.render(AdaptiveCardRenderer.java:94)
        at com.example.mobilechatapp.RecyclerViewContent$CardRendererTask.doInBackground(RecyclerViewContent.java:32)
        at com.example.mobilechatapp.RecyclerViewContent$CardRendererTask.doInBackground(RecyclerViewContent.java:19)
        at android.os.AsyncTask$2.call(AsyncTask.java:316)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:255) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:776) `

**Comment by paulcam206** [comment]
For the build issue, I ran across that but haven't put in a fix yet. You can build against the latest NDK by upgrading gradle in our project (or you can just cherry-pick commit 30842a5dfd87a846129ee4cda97ff4f420d5af88).

**Comment by shalinijoshi19** [comment]
@paulcam206 , @almedina-ms : Anything from our side that is still needed here for this one? 
@ThomasNeolink are you continuing to see this issue at your end?

**Comment by paulcam206** [comment]
> @paulcam206 : Anything from our side that is still needed here for this one?

I only dropped in on the thread to acknowledge the build issue. It's been resolved. As for the rest, I'll let @almedina-ms comment, but my guess is that this should be closed.
