### ISSUE TITLE
Deserializing a card twice in .NET fails with ID collision errors

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#3225]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET object model

# Author or host

Someone deserializing cards (issue was reported by internal MS customer)

# Version of SDK

NuGet 1.2.0

# Issue

If you use JSON.NET to deserialize a card that's within another object and then immediately deserialize the same card again, a collision ID occurs... even though it's deserializing two separate instances.

It seems like the collision ID logic is using a shared static or something when the AdaptiveCard isn't the top-level thing being deserialized.

**Repro code** (install latest .NET 1.2.0 from NuGet)

```csharp
public class cards
{
    public AdaptiveCard Card { get; set; }
}

private void Test()
{
    string cardsJson = @"{ ""card"": {
""type"": ""AdaptiveCard"",
""version"": ""1.0"",
""body"": [
{
    ""type"": ""Input.Text"",
    ""id"": ""myTextInput""
}
]
} }";

    cards fullcardresponse = JsonConvert.DeserializeObject<cards>(cardsJson);

    // Deserialize again, exception gets thrown here
    fullcardresponse = JsonConvert.DeserializeObject<cards>(cardsJson);
}
```

```
AdaptiveCards.AdaptiveSerializationException: 'Collision detected for id 'myTextInput''
```

# Workaround

If you use the official `AdaptiveCard.FromJson` method, it works fine. This problem is limited to deserializing a JSON object that inside it contains an Adaptive Card. So workaround is that you could parse the initial object and then grab the card as a JObject and then parse that using the official parsing method

**Comment by shalinijoshi19** [comment]
@paulcam206 mind taking a stab at this since you are the id collision guru :)  thanks!

**Comment by sguryev** [comment]
I have faced similar problem. I have read Card from JSON using `AdaptiveCard.FromJson()` method. I have there an `AdapriveContainer` which I should repeat undetermined number of times (based on object count read from DB). I was not able to find anything like `Clone` or `CopyFrom` method to clone my template `AdaptiveContainer`. So I have decided to Serialize and Deserialize object to create a new instance. 
Code 
`var clonedContainer = JsonConvert.DeserializeObject<AdaptiveContainer>(JsonConvert.SerializeObject(contactContainer));`
worked on version 1.0.0 but stopped on version 1.2.2

I have tried workaround above
```
var containerString = JsonConvert.SerializeObject(contactContainer);
var jObject = JObject.Parse(containerString);
var clonedContainer = jObject.ToObject<AdaptiveContainer>();
```
with no luck. Same issue with collision detected on first `AdaptiveTextBlock` element.

**Comment by pranag** [comment]
we got around this problem by putting the FromJson function within a semaphore wait block as below

```

_semaphore.WaitOne();
            try
            {
                var jsonCard = AdaptiveCard.FromJson(json);
                return jsonCard.Card;
            }
            finally
            {
                _semaphore.Release();
            }

```

this function is in itself within a singleton class

**Comment by sguryev** [comment]
Strange. I'm pretty sure I had a single thread there

**Comment by abbodh** [comment]
Has someone found out the solution?

**Comment by NickEricson** [comment]
I am using AdaptiveCard 1.2.4 and can't reproduce this using the original issue. Was this fixed?

**Comment by ericrrichards** [comment]
I've got this issue still occurring with the 2.1.0 Nuget package.
I have a List<AdaptiveElement> that is deserialized from json with JSON.net that is pulled from a database, and then injected into a card, e.g.

```
public AdaptiveCard MakeCard(string dbJson){
    var elements = JsonConvert.DeserializeObject<List<AdaptiveElement>>(dbJson);
    var card = new AdaptiveCard("1.2);
    card.Body.AddRange(elements);
    // other stuff...
    return card;
}
```

It'll work the first time, and then on subsequent calls this will throw the "collision detected for id "foo"" exception when doing DeserializeObject().

**Comment by NickEricson** [comment]
I hit this with the following card.

C# AdaptiveCard: 1.2.4
Using: AdaptiveCard.OnDeserializingMissingVersion = () => new AdaptiveSchemaVersion(0, 5);

```
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "What color do you want? *(isMultiSelect:false, style:compact)*"
        },
        {
            "type": "Input.ChoiceSet",
            "id": "myColor",
            "style": "compact",
            "isMultiSelect": false,
            "value": "1",
            "choices": [
                {
                    "title": "Red",
                    "value": "1",
                    "isSelected": true
                },
                {
                    "title": "Green",
                    "value": "2"
                },
                {
                    "title": "Blue",
                    "value": "3"
                }
            ]
        },
        {
            "type": "TextBlock",
            "text": "What color do you want? *(isMultiSelect:false, style:compact)*"
        },
        {
            "type": "Input.ChoiceSet",
            "id": "myColor2",
            "style": "expanded",
            "isMultiSelect": false,
            "value": "1",
            "choices": [
                {
                    "title": "Red",
                    "value": "1",
                    "isSelected": true
                },
                {
                    "title": "Green",
                    "value": "2"
                },
                {
                    "title": "Blue",
                    "value": "3"
                }
            ]
        },
        {
            "type": "TextBlock",
            "text": "What colors do you want? *(isMultiSelect:true, style:compact)*"
        },
        {
            "type": "Input.ChoiceSet",
            "id": "myColor3",
            "isMultiSelect": true,
            "value": "1,3",
            "style": "compact",
            "choices": [
                {
                    "title": "Red",
                    "value": "1",
                    "isSelected": true
                },
                {
                    "title": "Green",
                    "value": "2"
                },
                {
                    "title": "Blue",
                    "value": "3",
                    "isSelected": true
                }
            ]
        },
        {
            "type": "TextBlock",
            "text": "What colors do you want? *(isMultiSelect:true, style:expanded)*"
        },
        {
            "type": "Input.ChoiceSet",
            "id": "myColor3",
            "isMultiSelect": true,
            "value": "1",
            "style": "compact",
            "choices": [
                {
                    "title": "Red",
                    "value": "1",
                    "isSelected": true
                },
                {
                    "title": "Green",
                    "value": "2"
                },
                {
                    "title": "Blue",
                    "value": "3",
                    "isSelected": true
                }
            ]
        }
    ]
}
```

**Comment by naramaka** [comment]
Any update or closure on this issue ? I am facing it. and every time it gives different error.

**Comment by ericrrichards** [comment]
It's absurd, but this sort of thing is the solution that I've found to get around this kind of issue, in case it helps anyone else:

```csharp
var bodyJson = "..."; /* serialized list of AdaptiveElements making up the card body*/ 
var cardJson = $"{{\"type\": \"AdaptiveCard\",\"body\": {bodyJson},\"version\": \"1.2\"}}";
var parsed = AdaptiveCard.FromJson(cardJson);
var card = parsed.Card;
```

**Comment by nadoylemsft** [comment]
In an Azure Bot (webchat/directline channel only) I have a custom middleware that adds an OnSendActivityAsync handler. A waterfall dialog produces an Adaptive Card with a ChoiceInput with an Id of "Text". The first time this occurs there are no issues and submission works as intended.
On all subsequent submissions, the middleware runs and when attempting to load state from CosmosDB, the Collision occurs.

Finishing the dialog and sending a similar message in the same conversation to trigger the dialog again returns a new card and submitting the second card produces the issue.
After the first person has received the card and submitted, all users across all conversations receive this issue.

Multiuser conversations do not exist.

Stack trace after the middleware calls to load state from storage. 

```
AdaptiveCards.AdaptiveSerializationException: Collision detected for id 'Text'
   at AdaptiveCards.ParseContext.PopElement()
   at AdaptiveCards.AdaptiveTypedElementConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at AdaptiveCards.IgnoreEmptyItemsConverter`1.&lt;&gt;c__DisplayClass1_0.&lt;ReadJson&gt;b__1(JObject obj)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at AdaptiveCards.IgnoreEmptyItemsConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type&amp; objectType, JsonContract&amp; contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object&amp; newValue, String&amp; id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type&amp; objectType, JsonContract&amp; contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object&amp; newValue, String&amp; id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type&amp; objectType, JsonContract&amp; contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object&amp; newValue, String&amp; id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Microsoft.Bot.Builder.Azure.CosmosDbPartitionedStorage.ReadAsync(String[] keys, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotState.LoadAsync(ITurnContext turnContext, Boolean force, CancellationToken cancellationToken)
```

**Comment by nadoylemsft** [comment]
I was able to stop this from occurring by setting the Attachment Content as card.ToJson() instead of straight to card

```C#
//Added .ToJson() 
prompt.Attachments.Add(new Attachment { ContentType = AdaptiveCard.ContentType, Content = card.ToJson() });
```
