### ISSUE TITLE
Sending Adaptive Card in Teams with imBack doesnt work

### ISSUE THREAD

**Issue by adrianlubitz** [microsoft/AdaptiveCards#3262]
# Platform

NodeJS

# Author or host

I'm sending a card to my own bot that should use `imBack` to send a text back to the bot.

# Version of SDK
"botbuilder": "^3.11.0",
"botbuilder-teams": "^0.2.6",

# Issue

I'm trying to send the following Message

```js
                    msg = {
                        "type": "message",
                        "text": "Plain text is ok, but sometimes I long for more...",
                        "attachments": [
                          {
                            "contentType": "application/vnd.microsoft.card.adaptive",
                            "content": {
                              "type": "AdaptiveCard",
                              "version": "1.0",
                              "body": [
                                {
                                  "type": "TextBlock",
                                  "text": "Hello World!",
                                  "size": "large"
                                },
                                {
                                  "type": "TextBlock",
                                  "text": "*Sincerely yours,*"
                                },
                                {
                                  "type": "TextBlock",
                                  "text": "Adaptive Cards",
                                  "separation": "none"
                                }
                              ],
                              "actions": [
                                {
                                    "type": "imBack",
                                    "title": "More",
                                    "value": "Show me more"
                                }
                              ]
                            }
                          }
                        ]
                      };
```
(adapted sample from https://docs.microsoft.com/en-us/adaptive-cards/getting-started/bots#step-1-add-an-adaptive-card-attachment)

It throws the following error:
```
Error: POST to 'https://smba.trafficmanager.net/emea/v3/conversations/a%3A1dvlRZ6eNEws6sPoVszoWV92gErB5ac7axTPNciokCEPtcEr8YBF0vPRPCWjPmm4Dda70qnBCGt1uMbgBxC0HUjZMcuJ8NeXivy_FBUPO9kwpipF2rmZtSlTRKZuu3PaB/activities/1564411146824' failed: [400] Bad Request
    at Request._callback (/home/al/repos/msteams-samples-hello-world-nodejs/node_modules/botbuilder-teams/node_modules/botbuilder/lib/bots/ChatConnector.js:675:46)
    at Request.self.callback (/home/al/repos/msteams-samples-hello-world-nodejs/node_modules/botbuilder-teams/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/home/al/repos/msteams-samples-hello-world-nodejs/node_modules/botbuilder-teams/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/home/al/repos/msteams-samples-hello-world-nodejs/node_modules/botbuilder-teams/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

The sample I took it from works fine. Only if I try to use imBack as type it is not working.
It seems like it is somehow denying access. But that doesnt make sense to me because its sending a message to itself.

Hope someone knows a fix to it! I really need buttons in the bot, that send a message back to itself.

Thanks!
Adrian

**Comment by adrianlubitz** [comment]
Teams uses the following syntax:
```js
{ "type": "Action.Submit", "title": "Click me for imBack", "data": { "msteams": { "type": "imBack", "value": "Text to reply in chat" } } }
```
There was actually an example but it was confusingly on the very bottom of the site
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-actions#example-1

closing it because it was no issue just me not seeing it
