### ISSUE TITLE
[Javascript] TypeError: Cannot read property 'isValid' of undefined

### ISSUE THREAD

**Issue by scottlovegrove** [microsoft/AdaptiveCards#4767]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* JavaScript

# Author or host

Author

If you're an author, who are you sending cards to?

Custom renderer, but not important for this bug

# Version of SDK

2.3.0 of adaptivecards on npm

# Details

If I try and return an adaptive card as part of an API response, and the adaptive card isn't the root item, I'm getting the following error:

```
TypeError: Cannot read property 'isValid' of undefined
    at Version.compareTo (D:\doist\adaptivecards-repro\node_modules\adaptivecards\src\serialization.ts:66:44)
    at AdaptiveCard.SerializableObject.internalToJSON (D:\doist\adaptivecards-repro\node_modules\adaptivecards\src\serialization.ts:870:75)
    at AdaptiveCard.Container.internalToJSON (D:\doist\adaptivecards-repro\node_modules\adaptivecards\src\card-elements.ts:5449:29)
    at AdaptiveCard.ContainerWithActions.internalToJSON (D:\doist\adaptivecards-repro\node_modules\adaptivecards\src\card-elements.ts:6157:29)
    at AdaptiveCard.internalToJSON (D:\doist\adaptivecards-repro\node_modules\adaptivecards\src\card-elements.ts:6424:29)
    at AdaptiveCard.SerializableObject.toJSON (D:\doist\adaptivecards-repro\node_modules\adaptivecards\src\serialization.ts:913:18)
    at AdaptiveCard.CardElement.toJSON (D:\doist\adaptivecards-repro\node_modules\adaptivecards\src\card-elements.ts:326:28)
    at AdaptiveCard.toJSON (D:\doist\adaptivecards-repro\node_modules\adaptivecards\src\card-elements.ts:6548:28)
    at JSON.stringify (<anonymous>)
    at stringify (D:\doist\adaptivecards-repro\node_modules\express\lib\response.js:1123:12)
```

I've managed to create a repro project with this in. Just run `npm i && npm run start` then point to `http://localhost:4001/card` to reproduce
[adaptivecards-repro.zip](https://github.com/microsoft/AdaptiveCards/files/5210152/adaptivecards-repro.zip)

The key part to reproducing the problem is this:
```typescript
res.send({
        card: myAdaptiveCard,
    });
```
What then happens is `card` is passed through as the context of `toJSON` which results in the above error when comparing versions.

**Comment by shalinijoshi19** [comment]
@dclaux can you help take a look at this real quick ? Thanks

**Comment by dclaux** [comment]
@scottlovegrove wow that is due to a `toJSON()` quirk I wasn't aware of, but which is [documented on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) (namely that `toJSON()` gets passed a parameter when it is invoked automatically by `JSON.stringify()` - via `res.send()` in this case). The AC version of `toJSON()` takes an optional parameter of type `SerializationContext` and assumes that it is of that specific type if not undefined, which in your example isn't the case - the parameter is the string "card".

I will fix, but in the meantime you can work around the problem by explicitly calling `toJSON()` on your card first:
```typescript
    const adaptiveCard = new AdaptiveCard();
    adaptiveCard.version = new Version(1, 2);

    const textBlock = new TextBlock();
    textBlock.text = 'Sample';

    adaptiveCard.addItem(textBlock);

    let withThisItWillFail = {
        card: adaptiveCard
    }

    const serializedCard = adaptiveCard.toJSON();

    let withThisItWontFail = {
        card: serializedCard
    }

    JSON.stringify(withThisItWontFail);

```
