### ISSUE TITLE
[Android][Junit Failure] [Junit Fails for TimeFormatting Test function]

### ISSUE THREAD

**Issue by Anandsharmak** [microsoft/AdaptiveCards#4877]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* Android

# Author or host

This issue happened inside the android application for adaptive cards

# Version of SDK

latest main

# Details

Junit fails for TimeFormatting Test function. As in DateFormat some phones return Uppercase AM,PM whereas some return am, pm. And the assert is only against Uppercase AM, PM. Attaching below the error thrown

junit.framework.ComparisonFailure: expected:<7:15 [AM]> but was:<7:15 [am]>
at junit.framework.Assert.assertEquals(Assert.java:85)
at junit.framework.Assert.assertEquals(Assert.java:91)
at io.adaptivecards.objectmodel.TimeInputPropertiesTest.TimeFormatting(TimeInputPropertiesTest.java:203)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:384)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2209)

**Comment by Anandsharmak** [comment]
Can you assign this issue to me !

**Comment by almedina-ms** [comment]
Hi @Anandsharmak 

Thank you so much for raising this issue and submitting a fix, do you know if the AM/am issue happens because of the language the phone has, the android version or is it just an issue regarding different phone brands?

**Comment by Anandsharmak** [comment]
> Hi @Anandsharmak
> 
> Thank you so much for raising this issue and submitting a fix, do you know if the AM/am issue happens because of the language the phone has, the android version or is it just an issue regarding different phone brands?

I was using samsung phone for the junit , samsung uses its own framework maybe that might be the reason or it might be location based.

**Comment by shalinijoshi19** [comment]
@almedina-ms assigning to you to help get this merged in.

**Comment by almedina-ms** [comment]
Already merged
