### ISSUE TITLE
System.Exception: Unknown type FactSet in AdaptiveCards.Rendering.RenderContext.GetElementSeparation

### ISSUE THREAD

**Issue by svm-git** [Microsoft/AdaptiveCards#527]
System.Exception was unhandled
  HResult=-2146233088
  Message=Unknown type FactSet
  Source=AdaptiveCards.Html
  StackTrace:
       at AdaptiveCards.Rendering.RenderContext.GetElementSeparation(TypedElement element)
       at AdaptiveCards.Rendering.HtmlRenderer.AddContainerElements(HtmlTag uiContainer, List`1 elements, List`1 actions, RenderContext context)
       at AdaptiveCards.Rendering.HtmlRenderer.ContainerRender(TypedElement element, RenderContext context)
       at AdaptiveCards.Rendering.RenderContext.Render(TypedElement element)
       at AdaptiveCards.Rendering.HtmlRenderer.AddContainerElements(HtmlTag uiContainer, List`1 elements, List`1 actions, RenderContext context)
       at AdaptiveCards.Rendering.HtmlRenderer.AdaptiveCardRender(TypedElement element, RenderContext context)
       at AdaptiveCards.Rendering.RenderContext.Render(TypedElement element)
       at AdaptiveCards.Rendering.HtmlRenderer.RenderAdaptiveCard(AdaptiveCard card)

**Comment by matthidinger** [comment]
This should be fixed now in the latest AdaptiveCards.Rendering.Html package. If you're still seeing the issue could you please provide your payload and re-open? Thanks!
