### ISSUE TITLE
[Rendering] TypeError: Cannot read property 'Expression' of undefined (JS via CDN)

### ISSUE THREAD

**Issue by blinkbat** [microsoft/AdaptiveCards#6257]
### Target Platforms

Other

### SDK Version

Latest JS via CDN

### Application Name

JS test

### Problem Description

using AC via CDN, I am unable to .expand() a template given a data object.

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AC Test</title>

    <script src="https://unpkg.com/adaptivecards/dist/adaptivecards.js"></script>
    <script src="https://unpkg.com/adaptivecards-templating/dist/adaptivecards-templating.min.js"></script>
</head>
<body>
    
<script type="text/javascript">

window.createAndRenderCard = (template, data) => {

        // Create a Template instance from the template payload
        const cardTemplate = new ACData.Template(JSON.parse(template));
        // Expand the template 
        const cardPayload = cardTemplate.expand(JSON.parse(data));

        // Create an AdaptiveCard instance
        const adaptiveCard = new AdaptiveCards.AdaptiveCard();
        // Parse the card payload
        adaptiveCard.parse(cardPayload);
        // Render the card to an HTML element:
        const renderedCard = adaptiveCard.render();
        // And finally insert it somewhere in your page:
        document.body.appendChild(renderedCard);

}

createAndRenderCard(
  JSON.stringify({ "type": "AdaptiveCard", "version": "1.0", "body": [ { "type": "TextBlock", "text": "Hello !" } ] }),
  JSON.stringify({ "$root": { "name": "Matt Hidinger" } }),
);

</script>

</body>
</html>
```

The error that occurs:

TypeError: Cannot read property 'Expression' of undefined
at e.internalExpand (https://unpkg.com/adaptivecards-templating/dist/adaptivecards-templating.min.js:1:4924)
at e.expand (https://unpkg.com/adaptivecards-templating/dist/adaptivecards-templating.min.js:1:5788)
at window.createAndRenderCard

### Card JSON

JSON
{ "type": "AdaptiveCard", "version": "1.0", "body": [ { "type": "TextBlock", "text": "Hello ${name}!" } ] }
{ "$root": { "name": "Matt Hidinger" } }

**Comment by RebeccaAnne** [comment]
We don't explicitly support this scenario. Our supported means of consumption is via npm.
