### ISSUE TITLE
Must use import to load ES Module: swiper.esm.js

### ISSUE THREAD

**Issue by mectors** [microsoft/AdaptiveCards#8319]
# Platform
* JavaScript

# Author or host
Yes

# Version of SDK
    "adaptive-expressions": "^4.19.1",
    "adaptivecards": "^2.11.2",
    "adaptivecards-templating": "^2.3.1",
    "swiper": "^9.0.5"

# Issue
I am trying for adaptivecards templates to work consistently and I get really strange issues with some cards. So I just tried to make a very simple js script to test different templates with data. Unfortunately I get problems with carousel.js trying to use swiper which for some reason I had to add manually.

internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: = ./adaptivetemplating/node_modules/swiper/swiper.esm.js
require() of ES modules is not supported.
require() of ./adaptivetemplating/node_modules/swiper/swiper.esm.js from ./adaptivetemplating/node_modules/adaptivecards/lib/carousel.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename swiper.esm.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from ./adaptivetemplating/node_modules/swiper/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1131:13)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (./adaptivetemplating/node_modules/adaptivecards/lib/carousel.js:42:16)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32) {
  code: 'ERR_REQUIRE_ESM'
}

The code is simple and although not fully tested always gives the swiper error:
import * as ACData from "adaptivecards-templating";
import * as Adaptive from "adaptivecards";
var fs = require("fs");

console.log("template:",process.argv[2])
console.log("data:",process.argv[3])

const cardtemplate = fs.readFileSync(process.argv[2]);
const carddata  = fs.readFileSync(process.argv[3]);

var adaptiveCard = new Adaptive.AdaptiveCard();
var template = new ACData.Template(cardtemplate);
console.log("ctemplate:",template)
var context = {
}
context.$root = JSON.parse(carddata);
var cardPayload = template.expand(context);
console.log("card2:",cardPayload)
adaptiveCard.parse(cardPayload);
console.log(adaptiveCard.render());

A general comment on the actual usage of Adaptive Cards Templates [which I got working in a browser but not consistently takes all example files] is the 
var context: ACData.IEvaluationContext = {
    $root = {
        "name": "Adaptive Cards"
    }
};
where ACData.IEvaluationContext is not easy to get to work on javascript / nodejs / typescript.
It would be easier to have a ACData.Context(somejson)?

**Comment by MUCZ** [comment]
I have the exactly same problem :(

**Comment by proxy-hatch** [comment]
+1 also encountered this issue. Thanks for the workaround.

**Comment by meta-dipanshu-sharma** [comment]
I'm facing a similar issue while running jest unit tests when using `"adaptivecards": 2.11.2` version. Error is:

```
/node_modules/swiper/swiper.esm.js:13
    export { default as Swiper, default } from './core/core.js';
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (node_modules/adaptivecards/src/carousel.ts:26:1)
```

It works when we downgrades the version to `2.11.1` as suggested above but is there any fix coming up for latest version? Or is there any code workaround we can do while using latest?

**Comment by meta-dipanshu-sharma** [comment]
@jwoo-msft any updates on this?

**Comment by Neeraj-swarnkar** [comment]
@jwoo-msft @anna-dingler,
I was also getting similar error while running jest unit tests when using "adaptivecards": 2.11.2 version. So I have degraded and using below versions, and jest seems to work fine, But I am noticing issues with drag and drop feature. Getting below attached error, do we have any solution for that. 

        "adaptive-expressions": "4.19.3",
        "adaptivecards": "2.11.1",
        "adaptivecards-designer": "2.4.3",
        "adaptivecards-templating": "2.3.1",
  
![image](https://github.com/microsoft/AdaptiveCards/assets/3918217/bc9c52aa-1fb9-4f9d-b961-35ce2d568f38)

**Comment by Neeraj-swarnkar** [comment]
> @jwoo-msft @anna-dingler, @proxy-hatch @MUCZ I was also getting similar error while running jest unit tests when using "adaptivecards": 2.11.2 version. So I have degraded and using below versions, and jest seems to work fine, But I am noticing issues with drag and drop feature. Getting below attached error, do we have any solution for that.
> 
> ```
>     "adaptive-expressions": "4.19.3",
>     "adaptivecards": "2.11.1",
>     "adaptivecards-designer": "2.4.3",
>     "adaptivecards-templating": "2.3.1",
> ```
> 
> ![Screenshot 2023-05-15 at 10 39 55 PM](https://user-images.githubusercontent.com/3918217/238536140-19401c87-32ae-4d83-b3b2-3bd2c86639d7.png)
> 
> These versions are compatible ? When we have downgraded the adaptivecards version, should we downgrade the versions for other packages as well. Please confirm. Thanks..

@anna-dingler, @jwoo-msft Could you please suggest something.. Thanks..

**Comment by anna-dingler** [comment]
Hi @Neeraj-swarnkar,

I don't have a direct solution to this problem. The issue stems from `swiper` because it is an ES module. I created an issue related to this for our unit test project that includes some resources: https://github.com/microsoft/AdaptiveCards/issues/7983

I believe there should be some options for configuring your project to allow ES modules. Downgrading `swiper` to version 6 would also solve this.

I will speak with @jwoo-msft about bandwidth for this issue - thanks!

**Comment by Neeraj-swarnkar** [comment]
> Hi @Neeraj-swarnkar,
> 
> I don't have a direct solution to this problem. The issue stems from `swiper` because it is an ES module. I created an issue related to this for our unit test project that includes some resources: #7983
> 
> I believe there should be some options for configuring your project to allow ES modules. Downgrading `swiper` to version 6 would also solve this.
> 
> I will speak with @jwoo-msft about bandwidth for this issue - thanks!

Thanks @anna-dingler, UT issue is not coming with the swiper version 6.8.1.

**Comment by jwoo-msft** [comment]
The Swiper module we are currently dependent on only supports ESM (ECMAScript modules). To address this issue, you'll need to update your environment and source code to accommodate ESM modules.

This will be the quickest solution to the problem at hand. Meanwhile, we are working on an alternate resolution for developers who aren't yet able to utilize ESM. We plan to internally integrate Swiper into the AdaptiveCards and implement tree shaking.

As a result, developers will no longer need to directly depend on Swiper. However, this process will take some time. Therefore, we strongly recommend updating your environment and source code to support ESM in the interim.

**Comment by Katli95** [comment]
Unfortunately that's not really a viable solution for everyone. For my use-case I'm only using the library for card-generation, and with this development I'm leaning more towards abandoning the library entirely and making a proprietary JSON generation utility 😶

Will stay subscribed in the hopes for some pivot from this stance..

**Comment by domix1996** [comment]
any news?

**Comment by hughyyyy** [comment]
Hey @jwoo-msft, @anna-dingler 
Any news on this?

**Comment by JoA-MoS** [comment]
I believe the core of the problem is how the library is being packaged as a commonjs package via webpack that is referencing swiper using require. You can look at the published library built output at `node_modules/adaptivecards/lib/carousel.js`

```js
var card_elements_1 = require("./card-elements");
var Enums = require("./enums");
var serialization_1 = require("./serialization");
var registry_1 = require("./registry");
var enums_1 = require("./enums");
var strings_1 = require("./strings");
var swiper_1 = require("swiper");
var Utils = require("./utils");
var shared_1 = require("./shared");
```

There isn't much that any consuming application will be able to do to solve this. This is something that needs to be solved by the package owner.

One solution consumers can use is to use the package.json overrides property to downgrade swiper to `^6`, you can do this with the following snippet added to your package.json.

```jsonc
{
  "dependencies": {
    "adaptivecards": "^3.0.2"
    // other dependencies
  },
  "overrides": {
      "adaptivecards": {
          "swiper": "^6.0.0"
      }
  }
}
```

**Comment by csvtuda** [comment]
@jwoo-msft @paulcam206 Are there any news regarding this issue? The workaround provided by @JoA-MoS does not work anymore in version 3.0.5.

Minimal reproducible example:

```sh
#!/usr/bin/env bash

rm -r debug-directory
mkdir debug-directory
pushd debug-directory

npm init -y
npm pkg set type=module
npm pkg set overrides.adaptivecards.swiper="^6.0.0"
npm install adaptivecards

node -e 'import * as Adaptive from "adaptivecards"; console.log(Adaptive);'
popd
```

Output in 3.0.5:

```console
node:internal/modules/esm/resolve:257
    throw new ERR_MODULE_NOT_FOUND(
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Repositories\debug-directory\node_modules\adaptivecards\lib\strings' imported from C:\Repositories\debug-directory\node_modules\adaptivecards\lib\adaptivecards.js
    at finalizeResolution (node:internal/modules/esm/resolve:257:11)
    at moduleResolve (node:internal/modules/esm/resolve:913:10)
    at defaultResolve (node:internal/modules/esm/resolve:1037:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:650:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:599:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:582:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:241:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:132:49) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///C:/Repositories/debug-directory/node_modules/adaptivecards/lib/strings'
}

Node.js v22.11.0
```

**Comment by JoA-MoS** [comment]
@csvtuda - I believe your issue is with the strings package now. You could try pinning the AdaptiveCards package at an earlier version like the first comment in the thread.

**Comment by rido-min** [comment]
I'm trying with ES6 modules and still got this error.

Seems like there are some problems in `3.0.5`, and wondering if there is any other issue to track.

repro steps:


```json
{
  "type": "module",
  "dependencies": {
    "adaptivecards": "^3.0.5"
  }
}
```

```js
import { AdaptiveCard} from 'adaptivecards';

const myCard = new AdaptiveCard();
console.log(myCard);
```

Fails with

```
node:internal/modules/esm/resolve:257
    throw new ERR_MODULE_NOT_FOUND(
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'D:\source\adaptcards3test\node_modules\adaptivecards\lib\strings' imported from D:\source\adaptcards3test\node_modules\adaptivecards\lib\adaptivecards.js
    at finalizeResolution (node:internal/modules/esm/resolve:257:11)
    at moduleResolve (node:internal/modules/esm/resolve:913:10)
    at defaultResolve (node:internal/modules/esm/resolve:1037:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:650:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:599:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:582:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:241:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:132:49) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///D:/source/adaptcards3test/node_modules/adaptivecards/lib/strings'
}

Node.js v22.11.0
```
